package com.sample


import main.java.com.sample.Odpowiedz;
import main.java.com.sample.Pytanie;
import main.java.com.sample.Miasto;


rule "Poczatek"
    when

    then
       insert(new Pytanie());
       insert(new Miasto());
end

rule "Pierwsze pytanie"
    when
       Odpowiedz(text=="Europa");
       p:Pytanie();
    then
       p.ask("Co lubisz jesc?",new String[]{"Batony","Placki","Pďż˝czki"},0);
end

rule "Drugie pytanie"
    when
       Odpowiedz(text=="Europa");
       Odpowiedz(text=="Placki");
       p:Pytanie();
    then
       p.ask("Wspinaczki czy spacerki?",new String[]{"Góry","Plaże","Paczki"},1);
end

rule "Trzecie pytanie"
    when
       Odpowiedz(text=="Polska");
       Odpowiedz(text=="Batony");
       p:Pytanie();
    then
       p.ask("Batony?",new String[]{"Góry","Plaże","Paczki"},0);
end

rule "Czwarte pytanie"
    when
       Odpowiedz(text=="Europa");
       Odpowiedz(text=="Placki");
       Odpowiedz(text=="Góry");
       Odpowiedz(text=="Plaże");
       p:Pytanie();
    then
       p.ask("Batony?",new String[]{"Góry","Plaże","Paczki"},0);
end


